# Generated by Django 4.2.2 on 2023-06-15 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs_gallery', '0002_audio'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='access_type',
            field=models.CharField(choices=[('protected', 'Protected'), ('private', 'Private'), ('public', 'Public')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
